In [ ]:
# list_data = [1,2,3,4,5,6]: this is single dimension data
# numpy is used for multi dimensional data
# pip install numpy
# uv add numpy

In [2]:
import numpy as np


In [ ]:
arr_1d = np.array([1,2,3,4,5,6]) # 1D array
arr_1d

array([1, 2, 3, 4, 5, 6])

In [ ]:
arr_2d = np.array([[1,2,3],[4,5,6]]) # 2D array
arr_2d

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
arr_nested = np.array([  # 3D array
    [[1,2,3], [4,5,6]],
    [[7,8,9],[10,11,12]]
])
arr_nested

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [ ]:
#list vs numpy array:
 #list is always 1d whereas numpy array is multi dimensional
   #list
py_list = [1,2,3]
print("python list multipication", py_list*2)

python list multipication [1, 2, 3, 1, 2, 3]


In [ ]:
#numpy
py_array = np.array([1,2,3]) #element wise multipication
print("python_array multiplication:", py_array * 2)

python_array multiplication: [2 4 6]


In [ ]:
#normal list
import time
start = time.time()
py_list = [i * 2 for i in range(100000)]
print("\n list operation time:", time.time()-start)


 list operation time: 0.0047795772552490234


In [ ]:
#numpy
start = time.time()
np_array = np.array(100000) * 2 # 2 is called scalar, we can perform vector multiplication
print("\n list operation time:" , time.time()-start)
# so numpy operations are faster than list operations



 list operation time: 0.00010466575622558594


In [16]:
start = time.time()
py_list2 = [i ** 3 for i in range(100000)]
print("\n list operation time:", time.time()-start)


 list operation time: 0.00970315933227539


In [17]:
start = time.time()
np_array2 = np.array(100000) ** 3
print("\n list operation time:" , time.time()-start)


 list operation time: 0.0001647472381591797


In [21]:
#number of dimensions in an array is called RANK
#Rank 0 (scalar)
a = np.array(10)
print(a.ndim)

0


In [22]:
# Rank 1 (vector)
b = np.array([1,2,3])
print(b.ndim)

1


In [27]:
# rank 2 (Matrix)
a = np.array([
    [1,2,3],
    [4,5,6,]
    ])
a.ndim

2

In [24]:
a.shape # shape gives out rows and columns
        # here above, there are two rows [],[] and each rows has 3 elements which is column

(2, 3)

In [28]:
c = np.array([      # a 5*5 matrix also rank 2 because the two dimensions are row and column
    [1,2,3,4,5],
    [6,7,8,9,10],
    [11,12,13,14,15],
    [16,17,18,19,20],
    [21,22,23,24,25]
])
c.ndim

2

In [29]:
c.shape


(5, 5)

In [30]:
zeros = np.zeros((3,4))
print("zero array: \n", zeros)

zero array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [32]:
zeros = np.zeros((4,5))
print("zero array: \n", zeros)

zero array: 
 [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [35]:
ones = (np.ones((4,5)))  # the ones are float right now
print("ones array: \n", ones)

ones array: 
 [[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [3]:
np.ones(shape = (4,5), dtype = "int") # this is how we get integer array

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [5]:
a = np.array([
     [1,2,3],
     [4,5,6]
 ])
print(a.sum(axis=0)) # 0 = column

[5 7 9]


In [4]:
a = np.array([
     [1,2,3],
     [4,5,6]
 ])
print(a.sum(axis=1)) # 1 = row

[ 6 15]


In [7]:
#random array
random = np.random.random((2,3))
print("random array: \n", random)


random array: 
 [[0.4760184  0.0219747  0.98702256]
 [0.57413646 0.54808984 0.31834073]]


In [ ]:
#numpy methods: method to create numpy
 #array()
 #zeros()
 #ones()
 #full()
 #arrange()
 #linspace()
 #diag()
 #eye()
 #identity()
 #random.rand()


In [8]:
# 1. array() → create from a Python list
arr1 = np.array([1, 2, 3, 4, 5])
print("array():", arr1)

# 2. zeros() → array filled with zeros
arr2 = np.zeros((2, 3))
print("zeros():\n", arr2)

# 3. ones() → array filled with ones
arr3 = np.ones((3, 2))
print("ones():\n", arr3)

array(): [1 2 3 4 5]
zeros():
 [[0. 0. 0.]
 [0. 0. 0.]]
ones():
 [[1. 1.]
 [1. 1.]
 [1. 1.]]


In [18]:
# 4. full() → array filled with a specific value
arr4 = np.full((2,7),7)
print("full():\n", arr4)

# 5. arange() → evenly spaced values within a range
arr5 = np.arange(0,10,2) #start = 0 , stop = 10, step = 2
print("arange():", arr5)

# 6. linspace() → evenly spaced values between two numbers
arr5 = np.linspace(0,1,5) #5 values between 0 and 1
print("linspace():", arr5)

# 7. diag() → create diagonal matrix
arr7 = np.diag([1,2,3])
print("diag():\n", arr7)

# 8. eye() → create matrix with ones on diagonal
arr8 = np.eye(3)
print("eye():\n", arr8) # eye() being a square

arr = np.eye(3,5)
print("eye():\n", arr) # eye() being a rectangle

# 9 identity() → create identity matrix : diagonal with ones and rest zeros
arr9 = np.identity(3) #identity()can only be square
print("identity():\n", arr9)

### eye() shape can be rectangle or square but identity() shape can only be square

# 10. random.rand() → random values between 0 and 1
arr10 = np.random.rand(2, 3)
print("random.rand():\n", arr10)

full():
 [[7 7 7 7 7 7 7]
 [7 7 7 7 7 7 7]]
arange(): [0 2 4 6 8]
linspace(): [0.   0.25 0.5  0.75 1.  ]
diag():
 [[1 0 0]
 [0 2 0]
 [0 0 3]]
eye():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
eye():
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]
identity():
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
random.rand():
 [[0.16253948 0.48782946 0.32386022]
 [0.91280883 0.14355569 0.5609329 ]]
